<?php
    namespace Database\Seeders;

    use Illuminate\Database\Seeder;
    use Illuminate\Support\Facades\DB as FacadesDB;

    class IconSeeder extends Seeder {
        public function run(): void {
            FacadesDB::table('resources')->insert([
                ['title'=>'Add Window','class'=>'i-Add-Window',],
                ['title'=>'Approved Window','class'=>'i-Approved-Window',],
                ['title'=>'Add Window','class'=>'i-Add-Window',],
                ['title'=>'Approved Window','class'=>'i-Approved-Window',],
                ['title'=>'Block Window','class'=>'i-Block-Window',],
                ['title'=>'Close Window','class'=>'i-Close-Window',],
                ['title'=>'Code Window','class'=>'i-Code-Window',],
                ['title'=>'Delete Window','class'=>'i-Delete-Window',],
                ['title'=>'Download Window','class'=>'i-Download-Window',],
                ['title'=>'Duplicate Window','class'=>'i-Duplicate-Window',],
                ['title'=>'Error 404 Window','class'=>'i-Error-404-Window',],
                ['title'=>'Favorite Window','class'=>'i-Favorite-Window',],
                ['title'=>'Font-Window','class'=>'i-Font-Window',],
                ['title'=>'Full View Window','class'=>'i-Full-View-Window',],
                ['title'=>'Height Window','class'=>'i-Height-Window',],
                ['title'=>'Home Window','class'=>'i-Home-Window',],
                ['title'=>'Info Window','class'=>'i-Info-Window',],
                ['title'=>'Loading Window','class'=>'i-Loading-Window',],
                ['title'=>'Lock Window','class'=>'i-Lock-Window',],
                ['title'=>'Love Window','class'=>'i-Love-Window',],
                ['title'=>'Maximize Window','class'=>'i-Maximize-Window',],
                ['title'=>'Minimize Maximize-Close-Window','class'=>'i-Minimize-Maximize-Close-Window',],
                ['title'=>'Minimize Window','class'=>'i-Minimize-Window',],
                ['title'=>'Navigation Left-Window','class'=>'i-Navigation-Left-Window',],
                ['title'=>'Navigation Right-Window','class'=>'i-Navigation-Right-Window',],
                ['title'=>'Network Window','class'=>'i-Network-Window',],
                ['title'=>'New Tab','class'=>'i-New-Tab',],
                ['title'=>'One Window','class'=>'i-One-Window',],
                ['title'=>'Refresh Window','class'=>'i-Refresh-Window',],
                ['title'=>'Remove Window','class'=>'i-Remove-Window',],
                ['title'=>'Restore Window','class'=>'i-Restore-Window',],
                ['title'=>'Save Window','class'=>'i-Save-Window',],
                ['title'=>'Settings Window','class'=>'i-Settings-Window',],
                ['title'=>'Share Window','class'=>'i-Share-Window',],
                ['title'=>'Sidebar Window','class'=>'i-Sidebar-Window',],
                ['title'=>'Split Four-Square-Window','class'=>'i-Split-Four-Square-Window',],
                ['title'=>'Split Horizontal-2-Window','class'=>'i-Split-Horizontal-2-Window',],
                ['title'=>'Split Horizontal','class'=>'i-Split-Horizontal',],
                ['title'=>'Split Vertical-2','class'=>'i-Split-Vertical-2',],
                ['title'=>'Split Vertical','class'=>'i-Split-Vertical',],
                ['title'=>'Split Window','class'=>'i-Split-Window',],
                ['title'=>'Time Window','class'=>'i-Time-Window',],
                ['title'=>'Touch Window','class'=>'i-Touch-Window',],
                ['title'=>'Two Windows','class'=>'i-Two-Windows',],
                ['title'=>'Upload Window','class'=>'i-Upload-Window',],
                ['title'=>'URL-Window','class'=>'i-URL-Window',],
                ['title'=>'Warning-Window','class'=>'i-Warning-Window',],
                ['title'=>'Width Window','class'=>'i-Width-Window',],
                ['title'=>'Window 2','class'=>'i-Window-2',],
                ['title'=>'Windows 2','class'=>'i-Windows-2',],
                ['title'=>'Cloud Sun','class'=>'i-Cloud-Sun',],
                ['title'=>'Cloud Weather','class'=>'i-Cloud-Weather',],
                ['title'=>'Clouds Weather','class'=>'i-Clouds-Weather',],
                ['title'=>'Drop','class'=>'i-Drop',],
                ['title'=>'Dry','class'=>'i-Dry',],
                ['title'=>'Fahrenheit','class'=>'i-Fahrenheit',],
                ['title'=>'Windsock','class'=>'i-Windsock',],
                ['title'=>'Film Video','class'=>'i-Film-Video',],
                ['title'=>'Film','class'=>'i-Film',],
                ['title'=>'Flash Video','class'=>'i-Flash-Video',],
                ['title'=>'HD Video','class'=>'i-HD-Video',],
                ['title'=>'Movie','class'=>'i-Movie',],
                ['title'=>'Old TV','class'=>'i-Old-TV',],
                ['title'=>'Reel','class'=>'i-Reel',],
                ['title'=>'Tripod and Video','class'=>'i-Tripod-and-Video',],
                ['title'=>'TV','class'=>'i-TV',],
                ['title'=>'Video 2','class'=>'i-Video-2',],
                ['title'=>'Video 3','class'=>'i-Video-3',],
                ['title'=>'Video 4','class'=>'i-Video-4',],
                ['title'=>'Video 5','class'=>'i-Video-5',],
                ['title'=>'Video 6','class'=>'i-Video-6',],
                ['title'=>'Video Photographer','class'=>'i-Video-Photographer',],
                ['title'=>'Video Tripod','class'=>'i-Video-Tripod',],
                ['title'=>'Video','class'=>'i-Video',],
                ['title'=>'Affiliate','class'=>'i-Affiliate',],
                ['title'=>'Background','class'=>'i-Background',],
                ['title'=>'Billing','class'=>'i-Billing',],
                ['title'=>'Control 2','class'=>'i-Control-2',],
                ['title'=>'Control','class'=>'i-Control',],
                ['title'=>'Crop 2','class'=>'i-Crop-2',],
                ['title'=>'Dashboard','class'=>'i-Dashboard',],
                ['title'=>'Duplicate Layer','class'=>'i-Duplicate-Layer',],
                ['title'=>'Filter 2','class'=>'i-Filter-2',],
                ['title'=>'Gear 2','class'=>'i-Gear-2',],
                ['title'=>'Gear','class'=>'i-Gear',],
                ['title'=>'Gears 2','class'=>'i-Gears-2',],
                ['title'=>'Gears','class'=>'i-Gears',],
                ['title'=>'Information','class'=>'i-Information',],
                ['title'=>'Layer Backward','class'=>'i-Layer-Backward',],
                ['title'=>'Layer Forward','class'=>'i-Layer-Forward',],
                ['title'=>'Library','class'=>'i-Library',],
                ['title'=>'Loading 2','class'=>'i-Loading-2',],
                ['title'=>'Loading 3','class'=>'i-Loading-3',],
                ['title'=>'Loading','class'=>'i-Loading',],
                ['title'=>'Magnifi Glass','class'=>'i-Magnifi-Glass',],
                ['title'=>'Magnifi Glass-','class'=>'i-Magnifi-Glass-',],
                ['title'=>'Magnifi Glass1','class'=>'i-Magnifi-Glass1',],
                ['title'=>'Share','class'=>'i-Share',],
                ['title'=>'Statistic','class'=>'i-Statistic',],
                ['title'=>'Support','class'=>'i-Support',],
                ['title'=>'Bicycle 2','class'=>'i-Bicycle-2',],
                ['title'=>'Bicycle','class'=>'i-Bicycle',],
                ['title'=>'Car 2','class'=>'i-Car-2',],
                ['title'=>'Car 3','class'=>'i-Car-3',],
                ['title'=>'Car Wheel','class'=>'i-Car-Wheel',],
                ['title'=>'Car','class'=>'i-Car',],
                ['title'=>'Gaugage 2','class'=>'i-Gaugage-2',],
                ['title'=>'Gaugage','class'=>'i-Gaugage',],
                ['title'=>'Helicopter 2','class'=>'i-Helicopter-2',],
                ['title'=>'Helicopter','class'=>'i-Helicopter',],
                ['title'=>'Helmet','class'=>'i-Helmet',],
                ['title'=>'Jeep 2','class'=>'i-Jeep-2',],
                ['title'=>'Jeep','class'=>'i-Jeep',],
                ['title'=>'Jet','class'=>'i-Jet',],
                ['title'=>'Motorcycle','class'=>'i-Motorcycle',],
                ['title'=>'Plane 2','class'=>'i-Plane-2',],
                ['title'=>'Plane','class'=>'i-Plane',],
                ['title'=>'Road 2','class'=>'i-Road-2',],
                ['title'=>'Road','class'=>'i-Road',],
                ['title'=>'Rocket','class'=>'i-Rocket',],
                ['title'=>'Sailing Ship','class'=>'i-Sailing-Ship',],
                ['title'=>'Scooter Front','class'=>'i-Scooter-Front',],
                ['title'=>'Scooter','class'=>'i-Scooter',],
                ['title'=>'Ship 2','class'=>'i-Ship-2',],
                ['title'=>'Ship','class'=>'i-Ship',],
                ['title'=>'Skateboard 2','class'=>'i-Skateboard-2',],
                ['title'=>'Skateboard','class'=>'i-Skateboard',],
                ['title'=>'Taxi-2','class'=>'i-Taxi-2',],
                ['title'=>'Taxi-Sign','class'=>'i-Taxi-Sign',],
                ['title'=>'Taxi','class'=>'i-Taxi',],
                ['title'=>'Tractor','class'=>'i-Tractor',],
                ['title'=>'Traffic Light-2','class'=>'i-Traffic-Light-2',],
                ['title'=>'traffic Light','class'=>'i-traffic-Light',],
                ['title'=>'Train-2','class'=>'i-Train-2',],
                ['title'=>'Train','class'=>'i-Train',],
                ['title'=>'Tram','class'=>'i-Tram',],
                ['title'=>'Truck','class'=>'i-Truck',],
                ['title'=>'Yacht','class'=>'i-Yacht',],
                ['title'=>'Double-Tap','class'=>'i-Double-Tap',],
                ['title'=>'Drag Down','class'=>'i-Drag-Down',],
                ['title'=>'Drag Left','class'=>'i-Drag-Left',],
                ['title'=>'Drag Right','class'=>'i-Drag-Right',],
                ['title'=>'Drag Up:','class'=>'i-Drag-Up',],
                ['title'=>'Drag','class'=>'i-Drag',],
                ['title'=>'Clock-3','class'=>'i-Clock-3',],
                ['title'=>'Clock-4','class'=>'i-Clock-4',],
                ['title'=>'Clock-Back','class'=>'i-Clock-Back',],
                ['title'=>'Clock-Forward','class'=>'i-Clock-Forward',],
                ['title'=>'Clock','class'=>'i-Clock',],
                ['title'=>'Old Clock','class'=>'i-Old-Clock',],
                ['title'=>'Over Time-2','class'=>'i-Over-Time-2',],
                ['title'=>'Over Time','class'=>'i-Over-Time',],
                ['title'=>'Sand watch-2','class'=>'i-Sand-watch-2',],
                ['title'=>'Sand watch','class'=>'i-Sand-watch',],
                ['title'=>'Stopwatch-2','class'=>'i-Stopwatch-2',],
                ['title'=>'Stopwatch','class'=>'i-Stopwatch',],
                ['title'=>'Time Backup','class'=>'i-Time-Backup',],
                ['title'=>'Medal 2','class'=>'i-Medal-2',],
                ['title'=>'Medal 3','class'=>'i-Medal-3',],
                ['title'=>'Medal','class'=>'i-Medal',],
                ['title'=>'Speach-Bubble-2','class'=>'i-Speach-Bubble-2',],
                ['title'=>'Speach Bubble-3','class'=>'i-Speach-Bubble-3',],
                ['title'=>'Speach Bubble-4','class'=>'i-Speach-Bubble-4',],
                ['title'=>'Speach Bubble-5','class'=>'i-Speach-Bubble-5',],
                ['title'=>'Speach Bubble-6','class'=>'i-Speach-Bubble-6',],
                ['title'=>'Speach Bubble-7','class'=>'i-Speach-Bubble-7',],
                ['title'=>'Speach Bubble-8','class'=>'i-Speach-Bubble-8',],
                ['title'=>'Speach Bubble-9','class'=>'i-Speach-Bubble-9',],
                ['title'=>'Speach Bubble-10','class'=>'i-Speach-Bubble-10',],
                ['title'=>'Speach Bubble-11','class'=>'i-Speach-Bubble-11',],
                ['title'=>'Speach Bubble-12','class'=>'i-Speach-Bubble-12',],
                ['title'=>'Speach Bubble-13','class'=>'i-Speach-Bubble-13',],
                ['title'=>'Speach Bubble-Asking','class'=>'i-Speach-Bubble-Asking',],
                ['title'=>'Speach Bubble-Dialog','class'=>'i-Speach-Bubble-Dialog',],
                ['title'=>'Speach Bubble','class'=>'i-Speach-Bubble',],
                ['title'=>'Speach Bubbles','class'=>'i-Speach-Bubbles',],
                ['title'=>'Aim','class'=>'i-Aim',],
                ['title'=>'Ask','class'=>'i-Ask',],
                ['title'=>'Bebo','class'=>'i-Bebo',],
                ['title'=>'Behance','class'=>'i-Behance',],
                ['title'=>'Betvibes','class'=>'i-Betvibes',],
                ['title'=>'Bing','class'=>'i-Bing',],
                ['title'=>'Blinklist','class'=>'i-Blinklist',],
                ['title'=>'Blogger','class'=>'i-Blogger',],
                ['title'=>'Brightkite','class'=>'i-Brightkite',],
                ['title'=>'Delicious','class'=>'i-Delicious',],
                ['title'=>'Deviantart','class'=>'i-Deviantart',],
                ['title'=>'Digg','class'=>'i-Digg',],
                ['title'=>'Diigo','class'=>'i-Diigo',],
                ['title'=>'Doplr','class'=>'i-Doplr',],
                ['title'=>'Dribble','class'=>'i-Dribble',],
                ['title'=>'Email','class'=>'i-Email',],
                ['title'=>'Evernote','class'=>'i-Evernote',],
                ['title'=>'Facebook 2','class'=>'i-Facebook-2',],
                ['title'=>'Facebook','class'=>'i-Facebook',],
                ['title'=>'Feedburner','class'=>'i-Feedburner',],
                ['title'=>'Flickr','class'=>'i-Flickr',],
                ['title'=>'Formspring','class'=>'i-Formspring',],
                ['title'=>'Forsquare','class'=>'i-Forsquare',],
                ['title'=>'Friendfeed','class'=>'i-Friendfeed',],
                ['title'=>'Friendster','class'=>'i-Friendster',],
                ['title'=>'Furl','class'=>'i-Furl',],
                ['title'=>'Google Buzz','class'=>'i-Google-Buzz',],
                ['title'=>'Google Plus','class'=>'i-Google-Plus',],
                ['title'=>'Google','class'=>'i-Google',],
                ['title'=>'Gowalla','class'=>'i-Gowalla',],
                ['title'=>'ICQ','class'=>'i-ICQ',],
                ['title'=>'ImDB','class'=>'i-ImDB',],
                ['title'=>'Instagram','class'=>'i-Instagram',],
                ['title'=>'Last-FM','class'=>'i-Last-FM',],
                ['title'=>'Like-2','class'=>'i-Like-2',],
                ['title'=>'Like','class'=>'i-Like',],
                ['title'=>'Linkedin 2','class'=>'i-Linkedin-2',],
                ['title'=>'Linkedin','class'=>'i-Linkedin',],
                ['title'=>'Livejournal','class'=>'i-Livejournal',],
                ['title'=>'Metacafe','class'=>'i-Metacafe',],
                ['title'=>'Mixx','class'=>'i-Mixx',],
                ['title'=>'Myspace','class'=>'i-Myspace',],
                ['title'=>'Newsvine','class'=>'i-Newsvine',],
                ['title'=>'Orkut','class'=>'i-Orkut',],
                ['title'=>'Picasa','class'=>'i-Picasa',],
                ['title'=>'Pinterest','class'=>'i-Pinterest',],
                ['title'=>'Plaxo','class'=>'i-Plaxo',],
                ['title'=>'Plurk','class'=>'i-Plurk',],
                ['title'=>'Posterous','class'=>'i-Posterous',],
                ['title'=>'QIK','class'=>'i-QIK',],
                ['title'=>'Reddit','class'=>'i-Reddit',],
                ['title'=>'Reverbnation','class'=>'i-Reverbnation',],
                ['title'=>'RSS','class'=>'i-RSS',],
                ['title'=>'Sharethis','class'=>'i-Sharethis',],
                ['title'=>'Shoutwire','class'=>'i-Shoutwire',],
                ['title'=>'Skype','class'=>'i-Skype',],
                ['title'=>'Soundcloud','class'=>'i-Soundcloud',],
                ['title'=>'Spurl','class'=>'i-Spurl',],
                ['title'=>'Stumbleupon','class'=>'i-Stumbleupon',],
                ['title'=>'Technorati','class'=>'i-Technorati',],
                ['title'=>'Tumblr','class'=>'i-Tumblr',],
                ['title'=>'Twitter 2','class'=>'i-Twitter-2',],
                ['title'=>'Twitter','class'=>'i-Twitter',],
                ['title'=>'Unlike 2','class'=>'i-Unlike-2',],
                ['title'=>'Unlike','class'=>'i-Unlike',],
                ['title'=>'Ustream','class'=>'i-Ustream',],
                ['title'=>'Viddler','class'=>'i-Viddler',],
                ['title'=>'Vimeo','class'=>'i-Vimeo',],
                ['title'=>'Wordpress','class'=>'i-Wordpress',],
                ['title'=>'Xanga','class'=>'i-Xanga',],
                ['title'=>'Xing','class'=>'i-Xing',],
                ['title'=>'Yahoo-Buzz','class'=>'i-Yahoo-Buzz',],
                ['title'=>'Yahoo','class'=>'i-Yahoo',],
                ['title'=>'Yelp','class'=>'i-Yelp',],
                ['title'=>'Youtube','class'=>'i-Youtube',],
                ['title'=>'Zootool','class'=>'i-Zootool',],
                ['title'=>'Bisexual','class'=>'i-Bisexual',],
                ['title'=>'Cancer1','class'=>'i-Cancer1',],
                ['title'=>'Couple Sign','class'=>'i-Couple-Sign',],
                ['title'=>'David Star','class'=>'i-David-Star',],
                ['title'=>'Family Sign','class'=>'i-Family-Sign',],
                ['title'=>'Female 2','class'=>'i-Female-2',],
                ['title'=>'Gey','class'=>'i-Gey',],
                ['title'=>'Heart','class'=>'i-Heart',],
                ['title'=>'Homosexual','class'=>'i-Homosexual',],
                ['title'=>'Inifity','class'=>'i-Inifity',],
                ['title'=>'Lesbian','class'=>'i-Lesbian',],
                ['title'=>'Lesbians','class'=>'i-Lesbians',],
                ['title'=>'Love','class'=>'i-Love',],
                ['title'=>'Male 2','class'=>'i-Male-2',],
                ['title'=>'Men','class'=>'i-Men',],
                ['title'=>'No Smoking','class'=>'i-No-Smoking',],
                ['title'=>'Paw','class'=>'i-Paw',],
                ['title'=>'Quotes 2','class'=>'i-Quotes-2',],
                ['title'=>'Quotes','class'=>'i-Quotes',],
                ['title'=>'Add Cart','class'=>'i-Add-Cart',],
                ['title'=>'Bag Coins','class'=>'i-Bag-Coins',],
                ['title'=>'Bag Items','class'=>'i-Bag-Items',],
                ['title'=>'Bar Code','class'=>'i-Bar-Code',],
                ['title'=>'Bitcoin','class'=>'i-Bitcoin',],
                ['title'=>'Car Coins','class'=>'i-Car-Coins',],
                ['title'=>'Car Items','class'=>'i-Car-Items',],
                ['title'=>'Cart Quantity','class'=>'i-Cart-Quantity',],
                ['title'=>'Cash register-2','class'=>'i-Cash-register-2',],
                ['title'=>'Cash Register','class'=>'i-Cash-Register',],
                ['title'=>'Checkout-Bag','class'=>'i-Checkout-Bag',],
                ['title'=>'Checkout-Basket','class'=>'i-Checkout-Basket',],
                ['title'=>'Checkout','class'=>'i-Checkout',],
                ['title'=>'Full Basket','class'=>'i-Full-Basket',],
                ['title'=>'Full Cart','class'=>'i-Full-Cart',],
                ['title'=>'Password shopping','class'=>'i-Password-shopping',],
                ['title'=>'Receipt 3','class'=>'i-Receipt-3',],
                ['title'=>'Receipt 4','class'=>'i-Receipt-4',],
                ['title'=>'Receipt','class'=>'i-Receipt',],
                ['title'=>'Remove Bag','class'=>'i-Remove-Bag',],
                ['title'=>'Remove Basket','class'=>'i-Remove-Basket',],
                ['title'=>'Remove Cart','class'=>'i-Remove-Cart',],
                ['title'=>'Shop 2','class'=>'i-Shop-2',],
                ['title'=>'Shop 3','class'=>'i-Shop-3',],
                ['title'=>'Shop 4','class'=>'i-Shop-4',],
                ['title'=>'Shop','class'=>'i-Shop',],
                ['title'=>'Shopping Bag','class'=>'i-Shopping-Bag',],
                ['title'=>'Shopping Basket','class'=>'i-Shopping-Basket',],
                ['title'=>'Shopping Cart','class'=>'i-Shopping-Cart',],
                ['title'=>'Tag 2','class'=>'i-Tag-2',],
                ['title'=>'Tag 3','class'=>'i-Tag-3',],
                ['title'=>'Tag 4','class'=>'i-Tag-4',],
                ['title'=>'Tag 5','class'=>'i-Tag-5',],
                ['title'=>'This Side Up','class'=>'i-This-Side-Up',],
                ['title'=>'Broke Link 2','class'=>'i-Broke-Link-2',],
                ['title'=>'Coding','class'=>'i-Coding',],
                ['title'=>'Consulting','class'=>'i-Consulting',],
                ['title'=>'Copyright','class'=>'i-Copyright',],
                ['title'=>'Idea 2','class'=>'i-Idea-2',],
                ['title'=>'Idea 3','class'=>'i-Idea-3',],
                ['title'=>'Internet 2','class'=>'i-Internet-2',],
                ['title'=>'Internet','class'=>'i-Internet',],
                ['title'=>'Link 2','class'=>'i-Link-2',],
                ['title'=>'Management','class'=>'i-Management',],
                ['title'=>'Monitor Analytics','class'=>'i-Monitor-Analytics',],
                ['title'=>'Monitoring','class'=>'i-Monitoring',],
                ['title'=>'Optimization','class'=>'i-Optimization',],
                ['title'=>'Search People','class'=>'i-Search-People',],
                ['title'=>'Tag','class'=>'i-Tag',],
                ['title'=>'Target Market','class'=>'i-Target-Market',],
                ['title'=>'Target','class'=>'i-Target',],
                ['title'=>'Testimonal','class'=>'i-Testimonal',],
                ['title'=>'Computer Secure','class'=>'i-Computer-Secure',],
                ['title'=>'Eye Scan','class'=>'i-Eye-Scan',],
                ['title'=>'Finger Print','class'=>'i-Finger-Print',],
                ['title'=>'Firewall','class'=>'i-Firewall',],
                ['title'=>'Key Lock','class'=>'i-Key-Lock',],
                ['title'=>'Laptop Secure','class'=>'i-Laptop-Secure',],
                ['title'=>'Layer 1','class'=>'i-Layer-1',],
                ['title'=>'532','class'=>'i-532',],
                ['title'=>'Lock 2','class'=>'i-Lock-2',],
                ['title'=>'Lock 3','class'=>'i-Lock-3',],
                ['title'=>'Lock','class'=>'i-Lock',],
                ['title'=>'Password Field','class'=>'i-Password-Field',],
                ['title'=>'Password','class'=>'i-Password',],
                ['title'=>'Police','class'=>'i-Police',],
                ['title'=>'Safe Box','class'=>'i-Safe-Box',],
                ['title'=>'Security Block','class'=>'i-Security-Block',],
                ['title'=>'Security Bug','class'=>'i-Security-Bug',],
                ['title'=>'Security Camera','class'=>'i-Security-Camera',],
                ['title'=>'Security Check','class'=>'i-Security-Check',],
                ['title'=>'Security Settings','class'=>'i-Security-Settings',],
                ['title'=>'Securiy Remove','class'=>'i-Securiy-Remove',],
                ['title'=>'Shield','class'=>'i-Shield',],
                ['title'=>'Smartphone Secure','class'=>'i-Smartphone--Secure',],
                ['title'=>'SSL','class'=>'i-SSL',],
                ['title'=>'Tablet-Secure','class'=>'i-Tablet-Secure',],
                ['title'=>'Type Pass','class'=>'i-Type-Pass',],
                ['title'=>'Unlock 2','class'=>'i-Unlock-2',],
                ['title'=>'Unlock 3','class'=>'i-Unlock-3',],
                ['title'=>'Unlock','class'=>'i-Unlock',],
                ['title'=>'Ambulance','class'=>'i-Ambulance',],
                ['title'=>'Atom','class'=>'i-Atom',],
                ['title'=>'Band Aid','class'=>'i-Band-Aid',],
                ['title'=>'Bio Hazard','class'=>'i-Bio-Hazard',],
                ['title'=>'Biotech','class'=>'i-Biotech',],
                ['title'=>'Brain','class'=>'i-Brain',],
                ['title'=>'Chemical 2','class'=>'i-Chemical-2',],
                ['title'=>'Chemical 3','class'=>'i-Chemical-3',],
                ['title'=>'Chemical 4','class'=>'i-Chemical-4',],
                ['title'=>'Chemical 5','class'=>'i-Chemical-5',],
                ['title'=>'Chemical','class'=>'i-Chemical',],
                ['title'=>'Clinic','class'=>'i-Clinic',],
                ['title'=>'Cube Molecule 2','class'=>'i-Cube-Molecule-2',],
                ['title'=>'Cube Molecule','class'=>'i-Cube-Molecule',],
                ['title'=>'Danger 2','class'=>'i-Danger-2',],
                ['title'=>'Danger','class'=>'i-Danger',],
                ['title'=>'First-Aid','class'=>'i-First-Aid',],
                ['title'=>'Flask 2','class'=>'i-Flask-2',],
                ['title'=>'Flask','class'=>'i-Flask',],
                ['title'=>'Helix 2','class'=>'i-Helix-2',],
                ['title'=>'Hospital','class'=>'i-Hospital',],
                ['title'=>'Medicine 2','class'=>'i-Medicine-2',],
                ['title'=>'Medicine 3','class'=>'i-Medicine-3',],
                ['title'=>'Medicine','class'=>'i-Medicine',],
                ['title'=>'Microscope','class'=>'i-Microscope',],
                ['title'=>'Neutron','class'=>'i-Neutron',],
                ['title'=>'Nuclear','class'=>'i-Nuclear',],
                ['title'=>'Physics','class'=>'i-Physics',],
                ['title'=>'Plasmid','class'=>'i-Plasmid',],
                ['title'=>'Pulse','class'=>'i-Pulse',],
                ['title'=>'Radioactive','class'=>'i-Radioactive',],
                ['title'=>'Stethoscope','class'=>'i-Stethoscope',],
                ['title'=>'Temperature 1','class'=>'i-Temperature1',],
                ['title'=>'Test Tube 2','class'=>'i-Test-Tube-2',],
                ['title'=>'Test Tube','class'=>'i-Test-Tube',],
                ['title'=>'Virus 2','class'=>'i-Virus-2',],
                ['title'=>'Virus 3','class'=>'i-Virus-3',],
                ['title'=>'Virus','class'=>'i-Virus',],
                ['title'=>'Camera','class'=>'i-Camera',],
                ['title'=>'Edit','class'=>'i-Edit',],
                ['title'=>'Eye','class'=>'i-Eye',],
                ['title'=>'Film Cartridge','class'=>'i-Film-Cartridge',],
                ['title'=>'Film1','class'=>'i-Film1',],
                ['title'=>'Filter','class'=>'i-Filter',],
                ['title'=>'Flash 2','class'=>'i-Flash-2',],
                ['title'=>'Flash','class'=>'i-Flash',],
                ['title'=>'Fluorescent','class'=>'i-Fluorescent',],
                ['title'=>'Gopro','class'=>'i-Gopro',],
                ['title'=>'Landscape','class'=>'i-Landscape',],
                ['title'=>'Len 2','class'=>'i-Len-2',],
                ['title'=>'Len 3','class'=>'i-Len-3',],
                ['title'=>'Len','class'=>'i-Len',],
                ['title'=>'Macro','class'=>'i-Macro',],
                ['title'=>'Memory Card 2','class'=>'i-Memory-Card-2',],
                ['title'=>'Memory Card 3','class'=>'i-Memory-Card-3',],
                ['title'=>'Memory Card','class'=>'i-Memory-Card',],
                ['title'=>'No-Flash','class'=>'i-No-Flash',],
                ['title'=>'Shutter','class'=>'i-Shutter',],
                ['title'=>'Signal','class'=>'i-Signal',],
                ['title'=>'Snow1','class'=>'i-Snow1',],
                ['title'=>'Sport Mode','class'=>'i-Sport-Mode',],
                ['title'=>'Studio Flash','class'=>'i-Studio-Flash',],
                ['title'=>'Studio Lightbox','class'=>'i-Studio-Lightbox',],
                ['title'=>'Timer1','class'=>'i-Timer1',],
                ['title'=>'Tripod 2','class'=>'i-Tripod-2',],
                ['title'=>'Tripod with Camera','class'=>'i-Tripod-with-Camera',],
                ['title'=>'Tripod with Gopro','class'=>'i-Tripod-with-Gopro',],
                ['title'=>'Add User','class'=>'i-Add-User',],
                ['title'=>'Add UserStar','class'=>'i-Add-UserStar',],
                ['title'=>'Administrator','class'=>'i-Administrator',],
                ['title'=>'Alien 2','class'=>'i-Alien-2',],
                ['title'=>'Alien','class'=>'i-Alien',],
                ['title'=>'Assistant','class'=>'i-Assistant',],
                ['title'=>'Baby Cry','class'=>'i-Baby-Cry',],
                ['title'=>'Baby','class'=>'i-Baby',],
                ['title'=>'Boy','class'=>'i-Boy',],
                ['title'=>'Business Man','class'=>'i-Business-Man',],
                ['title'=>'Business ManWoman','class'=>'i-Business-ManWoman',],
                ['title'=>'Business Mens','class'=>'i-Business-Mens',],
                ['title'=>'Business Woman','class'=>'i-Business-Woman',],
                ['title'=>'Checked User','class'=>'i-Checked-User',],
                ['title'=>'Chef','class'=>'i-Chef',],
                ['title'=>'Conference','class'=>'i-Conference',],
                ['title'=>'Cool Guy','class'=>'i-Cool-Guy',],
                ['title'=>'Criminal','class'=>'i-Criminal',],
                ['title'=>'Dj','class'=>'i-Dj',],
                ['title'=>'Doctor','class'=>'i-Doctor',],
                ['title'=>'Engineering','class'=>'i-Engineering',],
                ['title'=>'Farmer','class'=>'i-Farmer',],
                ['title'=>'Female 21','class'=>'i-Female-21',],
                ['title'=>'Female','class'=>'i-Female',],
                ['title'=>'Find User','class'=>'i-Find-User',],
                ['title'=>'Geek','class'=>'i-Geek',],
                ['title'=>'Genius','class'=>'i-Genius',],
                ['title'=>'Girl','class'=>'i-Girl',],
                ['title'=>'Headphone','class'=>'i-Headphone',],
                ['title'=>'Headset','class'=>'i-Headset',],
                ['title'=>'ID 2','class'=>'i-ID-2',],
                ['title'=>'ID 3','class'=>'i-ID-3',],
                ['title'=>'ID Card','class'=>'i-ID-Card',],
                ['title'=>'King 2','class'=>'i-King-2',],
                ['title'=>'Lock User','class'=>'i-Lock-User',],
                ['title'=>'Love User','class'=>'i-Love-User',],
                ['title'=>'Male 21','class'=>'i-Male-21',],
                ['title'=>'Male','class'=>'i-Male',],
                ['title'=>'MaleFemale','class'=>'i-MaleFemale',],
                ['title'=>'Man Sign','class'=>'i-Man-Sign',],
                ['title'=>'Mens','class'=>'i-Mens',],
                ['title'=>'Network','class'=>'i-Network',],
                ['title'=>'Nurse','class'=>'i-Nurse',],
                ['title'=>'Pilot','class'=>'i-Pilot',],
                ['title'=>'Professor','class'=>'i-Professor',],
                ['title'=>'Punker','class'=>'i-Punker',],
                ['title'=>'Remove User','class'=>'i-Remove-User',],
                ['title'=>'Robot','class'=>'i-Robot',],
                ['title'=>'Speak 2','class'=>'i-Speak-2',],
                ['title'=>'Speak','class'=>'i-Speak',],
                ['title'=>'Spy','class'=>'i-Spy',],
                ['title'=>'Student Female','class'=>'i-Student-Female',],
                ['title'=>'Student Male','class'=>'i-Student-Male',],
                ['title'=>'Student MaleFemale','class'=>'i-Student-MaleFemale',],
                ['title'=>'Students','class'=>'i-Students',],
                ['title'=>'Superman','class'=>'i-Superman',],
                ['title'=>'Talk-Man','class'=>'i-Talk-Man',],
                ['title'=>'Teacher','class'=>'i-Teacher',],
                ['title'=>'Coffee Machine','class'=>'i-Coffee-Machine',],
                ['title'=>'Flag 2','class'=>'i-Flag-2',],
                ['title'=>'Flag','class'=>'i-Flag',],
                ['title'=>'Flashlight','class'=>'i-Flashlight',],
                ['title'=>'Gas Pump','class'=>'i-Gas-Pump',],
                ['title'=>'Gift Box','class'=>'i-Gift-Box',],
                ['title'=>'Key 3','class'=>'i-Key-3',],
                ['title'=>'Key','class'=>'i-Key',],
                ['title'=>'Lamp','class'=>'i-Lamp',],
                ['title'=>'Life Safer','class'=>'i-Life-Safer',],
                ['title'=>'Light Bulb','class'=>'i-Light-Bulb',],
                ['title'=>'Luggage 2','class'=>'i-Luggage-2',],
                ['title'=>'Magnet','class'=>'i-Magnet',],
                ['title'=>'Mirror','class'=>'i-Mirror',],
                ['title'=>'Movie Ticket','class'=>'i-Movie-Ticket',],
                ['title'=>'Office Lamp','class'=>'i-Office-Lamp',],
                ['title'=>'Paint Brush','class'=>'i-Paint-Brush',],
                ['title'=>'Paint Bucket','class'=>'i-Paint-Bucket',],
                ['title'=>'Paper Plane','class'=>'i-Paper-Plane',],
                ['title'=>'Post Sign 2-ways','class'=>'i-Post-Sign-2-ways',],
                ['title'=>'Post Sign','class'=>'i-Post-Sign',],
                ['title'=>'Scale','class'=>'i-Scale',],
                ['title'=>'Stroller','class'=>'i-Stroller',],
                ['title'=>'Suitcase','class'=>'i-Suitcase',],
                ['title'=>'Teddy Bear','class'=>'i-Teddy-Bear',],
                ['title'=>'Telescope','class'=>'i-Telescope',],
                ['title'=>'Tent','class'=>'i-Tent',],
                ['title'=>'Thread','class'=>'i-Thread',],
                ['title'=>'Ticket','class'=>'i-Ticket',],
                ['title'=>'Time Bomb','class'=>'i-Time-Bomb',],
                ['title'=>'Tourch','class'=>'i-Tourch',],
                ['title'=>'Vase','class'=>'i-Vase',],
                ['title'=>'Video Game Controller','class'=>'i-Video-Game-Controller',],
                ['title'=>'Conservation','class'=>'i-Conservation',],
                ['title'=>'Eci Icon','class'=>'i-Eci-Icon',],
                ['title'=>'Environmental 2','class'=>'i-Environmental-2',],
                ['title'=>'Environmental 3','class'=>'i-Environmental-3',],
                ['title'=>'Green Energy','class'=>'i-Green-Energy',],
                ['title'=>'Green House','class'=>'i-Green-House',],
                ['title'=>'Landscape 1','class'=>'i-Landscape1',],
                ['title'=>'Leafs 2','class'=>'i-Leafs-2',],
                ['title'=>'Light Bulb Leaf','class'=>'i-Light-Bulb-Leaf',],
                ['title'=>'Palm Tree','class'=>'i-Palm-Tree',],
                ['title'=>'Plant','class'=>'i-Plant',],
                ['title'=>'Recycling 2','class'=>'i-Recycling-2',],
                ['title'=>'Tree 3','class'=>'i-Tree-3',],
                ['title'=>'Bell','class'=>'i-Bell',],
                ['title'=>'Casette Tape','class'=>'i-Casette-Tape',],
                ['title'=>'Drum','class'=>'i-Drum',],
                ['title'=>'Electric Guitar','class'=>'i-Electric-Guitar',],
                ['title'=>'First','class'=>'i-First',],
                ['title'=>'Keyboard 3','class'=>'i-Keyboard3',],
                ['title'=>'Last','class'=>'i-Last',],
                ['title'=>'Microphone 3','class'=>'i-Microphone-3',],
                ['title'=>'Music Note 2','class'=>'i-Music-Note-2',],
                ['title'=>'Next Music','class'=>'i-Next-Music',],
                ['title'=>'Old Radio','class'=>'i-Old-Radio',],
                ['title'=>'On Air','class'=>'i-On-Air',],
                ['title'=>'Play Music','class'=>'i-Play-Music',],
                ['title'=>'Stop Music','class'=>'i-Stop-Music',],
                ['title'=>'Trumpet','class'=>'i-Trumpet',],
                ['title'=>'Voice','class'=>'i-Voice',],
                ['title'=>'Pause 2','class'=>'i-Pause-2',],
                ['title'=>'Pause','class'=>'i-Pause',],
                ['title'=>'Power 2','class'=>'i-Power-2',],
                ['title'=>'Power 3','class'=>'i-Power-3',],
                ['title'=>'Record 2','class'=>'i-Record-2',],
                ['title'=>'Record 1','class'=>'i-Record1',],
                ['title'=>'Repeat 2','class'=>'i-Repeat-2',],
                ['title'=>'Repeat','class'=>'i-Repeat',],
                ['title'=>'Shuffle 2','class'=>'i-Shuffle-2',],
                ['title'=>'Shuffle','class'=>'i-Shuffle',],
                ['title'=>'Start 2','class'=>'i-Start-2',],
                ['title'=>'Start','class'=>'i-Start',],
                ['title'=>'Stop 2','class'=>'i-Stop-2',],
                ['title'=>'Stop','class'=>'i-Stop',],
                ['title'=>'Compass 2','class'=>'i-Compass-2',],
                ['title'=>'Compass Rose','class'=>'i-Compass-Rose',],
                ['title'=>'Edit Map','class'=>'i-Edit-Map',],
                ['title'=>'Geo 2','class'=>'i-Geo2-',],
                ['title'=>'Geo 21','class'=>'i-Geo21',],
                ['title'=>'Globe 2','class'=>'i-Globe-2',],
                ['title'=>'Globe','class'=>'i-Globe',],
                ['title'=>'Map Marker','class'=>'i-Map-Marker',],
                ['title'=>'Map','class'=>'i-Map',],
                ['title'=>'Map2','class'=>'i-Map2',],
                ['title'=>'Android Store','class'=>'i-Android-Store',],
                ['title'=>'Apple Store','class'=>'i-Apple-Store',],
                ['title'=>'Box 1','class'=>'i-Box1',],
                ['title'=>'Dropbox','class'=>'i-Dropbox',],
                ['title'=>'Google Drive','class'=>'i-Google-Drive',],
                ['title'=>'Google Play','class'=>'i-Google-Play',],
                ['title'=>'Paypal','class'=>'i-Paypal',],
                ['title'=>'Skrill','class'=>'i-Skrill',],
                ['title'=>'X-Box','class'=>'i-X-Box',],
                ['title'=>'Add','class'=>'i-Add',],
                ['title'=>'Back1','class'=>'i-Back1',],
                ['title'=>'Broken Link','class'=>'i-Broken-Link',],
                ['title'=>'Check','class'=>'i-Check',],
                ['title'=>'Circular Point','class'=>'i-Circular-Point',],
                ['title'=>'Close','class'=>'i-Close',],
                ['title'=>'Cursor Click 2','class'=>'i-Cursor-Click-2',],
                ['title'=>'Cursor Click','class'=>'i-Cursor-Click',],
                ['title'=>'Cursor Move 2','class'=>'i-Cursor-Move-2',],
                ['title'=>'Cursor Move','class'=>'i-Cursor-Move',],
                ['title'=>'Cursor Select','class'=>'i-Cursor-Select',],
                ['title'=>'Cursor','class'=>'i-Cursor',],
                ['title'=>'Down','class'=>'i-Down',],
                ['title'=>'Download','class'=>'i-Download',],
                ['title'=>'Downward','class'=>'i-Downward',],
                ['title'=>'Endways','class'=>'i-Endways',],
                ['title'=>'Forward','class'=>'i-Forward',],
                ['title'=>'Left','class'=>'i-Left',],
                ['title'=>'Link','class'=>'i-Link',],
                ['title'=>'Next 1','class'=>'i-Next1',],
                ['title'=>'Orientation','class'=>'i-Orientation',],
                ['title'=>'Pointer','class'=>'i-Pointer',],
                ['title'=>'Previous','class'=>'i-Previous',],
                ['title'=>'Redo','class'=>'i-Redo',],
                ['title'=>'Refresh','class'=>'i-Refresh',],
                ['title'=>'Reload','class'=>'i-Reload',],
                ['title'=>'Remove','class'=>'i-Remove',],
                ['title'=>'Repeat1','class'=>'i-Repeat1',],
                ['title'=>'Reset','class'=>'i-Reset',],
                ['title'=>'Rewind','class'=>'i-Rewind',],
                ['title'=>'Right','class'=>'i-Right',],
                ['title'=>'Rotation-390','class'=>'i-Rotation-390',],
                ['title'=>'Up','class'=>'i-Up',],
                ['title'=>'Upload','class'=>'i-Upload',],
                ['title'=>'Upward','class'=>'i-Upward',],
                ['title'=>'Yes','class'=>'i-Yes',],
                ['title'=>'Electricity','class'=>'i-Electricity',],
                ['title'=>'Factory','class'=>'i-Factory',],
                ['title'=>'Bag','class'=>'i-Bag',],
                ['title'=>'Bakelite','class'=>'i-Bakelite',],
                ['title'=>'Bicycle 1','class'=>'i-Bicycle1',],
                ['title'=>'Bow 2','class'=>'i-Bow-2',],
                ['title'=>'Bow 3','class'=>'i-Bow-3',],
                ['title'=>'Bow','class'=>'i-Bow',],
                ['title'=>'Hipster Glasses 2','class'=>'i-Hipster-Glasses-2',],
                ['title'=>'Hipster Glasses 3','class'=>'i-Hipster-Glasses-3',],
                ['title'=>'Hipster Glasses','class'=>'i-Hipster-Glasses',],
                ['title'=>'Hipster Headphones','class'=>'i-Hipster-Headphones',],
                ['title'=>'Hipster Men 2','class'=>'i-Hipster-Men-2',],
                ['title'=>'Hipster Men 3','class'=>'i-Hipster-Men-3',],
                ['title'=>'Hipster Men','class'=>'i-Hipster-Men',],
                ['title'=>'Hipster Sunglasses 2','class'=>'i-Hipster-Sunglasses-2',],
                ['title'=>'Hipster Sunglasses 3','class'=>'i-Hipster-Sunglasses-3',],
                ['title'=>'Hipster Sunglasses','class'=>'i-Hipster-Sunglasses',],
                ['title'=>'Jacket','class'=>'i-Jacket',],
                ['title'=>'Mustache 2','class'=>'i-Mustache-2',],
                ['title'=>'Mustache 3','class'=>'i-Mustache-3',],
                ['title'=>'Mustache','class'=>'i-Mustache',],
                ['title'=>'Old Camera','class'=>'i-Old-Camera',],
                ['title'=>'Old Cassette','class'=>'i-Old-Cassette',],
                ['title'=>'Old Sticky 2','class'=>'i-Old-Sticky-2',],
                ['title'=>'Old Sticky','class'=>'i-Old-Sticky',],
                ['title'=>'Disk','class'=>'i-Disk',],
                ['title'=>'Fan','class'=>'i-Fan',],
                ['title'=>'Gamepad 2','class'=>'i-Gamepad-2',],
                ['title'=>'Folder Add','class'=>'i-Folder-Add-',],
                ['title'=>'Folder Archive','class'=>'i-Folder-Archive',],
                ['title'=>'Folder Binder 2','class'=>'i-Folder-Binder-2',],
                ['title'=>'Folder Binder','class'=>'i-Folder-Binder',],
                ['title'=>'Folder Block','class'=>'i-Folder-Block',],
                ['title'=>'Folder Close','class'=>'i-Folder-Close',],
                ['title'=>'Folder Download','class'=>'i-Folder-Download',],
                ['title'=>'Folder Hide','class'=>'i-Folder-Hide',],
                ['title'=>'Folder Loading','class'=>'i-Folder-Loading',],
                ['title'=>'Folder Music','class'=>'i-Folder-Music',],
                ['title'=>'Folder Network','class'=>'i-Folder-Network',],
                ['title'=>'Folder Open 2','class'=>'i-Folder-Open-2',],
                ['title'=>'Folder Open','class'=>'i-Folder-Open',],
                ['title'=>'Folder Organizing','class'=>'i-Folder-Organizing',],
                ['title'=>'Folder Pictures','class'=>'i-Folder-Pictures',],
                ['title'=>'Folder Refresh','class'=>'i-Folder-Refresh',],
                ['title'=>'Folder Remove','class'=>'i-Folder-Remove',],
                ['title'=>'Folder Search','class'=>'i-Folder-Search',],
                ['title'=>'Folder Settings','class'=>'i-Folder-Settings',],
                ['title'=>'Folder Share','class'=>'i-Folder-Share',],
                ['title'=>'Folder Trash','class'=>'i-Folder-Trash',],
                ['title'=>'Folder Upload','class'=>'i-Folder-Upload',],
                ['title'=>'Folder Video','class'=>'i-Folder-Video',],
                ['title'=>'Folder With Document','class'=>'i-Folder-With-Document',],
                ['title'=>'Folder Zip','class'=>'i-Folder-Zip',],
                ['title'=>'Folder','class'=>'i-Folder',],
                ['title'=>'Folders','class'=>'i-Folders',],
                ['title'=>'Add File','class'=>'i-Add-File',],
                ['title'=>'Delete File','class'=>'i-Delete-File',],
                ['title'=>'File Block','class'=>'i-File-Block',],
                ['title'=>'File Bookmark','class'=>'i-File-Bookmark',],
                ['title'=>'File Chart','class'=>'i-File-Chart',],
                ['title'=>'File Clipboard File Text','class'=>'i-File-Clipboard-File--Text',],
                ['title'=>'File Clipboard Text Image','class'=>'i-File-Clipboard-Text--Image',],
                ['title'=>'File Clipboard','class'=>'i-File-Clipboard',],
                ['title'=>'File Cloud','class'=>'i-File-Cloud',],
                ['title'=>'File Copy 2','class'=>'i-File-Copy-2',],
                ['title'=>'File Copy','class'=>'i-File-Copy',],
                ['title'=>'File CSV','class'=>'i-File-CSV',],
                ['title'=>'File Download','class'=>'i-File-Download',],
                ['title'=>'File Edit','class'=>'i-File-Edit',],
                ['title'=>'File Excel','class'=>'i-File-Excel',],
                ['title'=>'File Favorite','class'=>'i-File-Favorite',],
                ['title'=>'File Fire','class'=>'i-File-Fire',],
                ['title'=>'File Graph','class'=>'i-File-Graph',],
                ['title'=>'File Hide','class'=>'i-File-Hide',],
                ['title'=>'File Horizontal Text','class'=>'i-File-Horizontal-Text',],
                ['title'=>'File Horizontal','class'=>'i-File-Horizontal',],
                ['title'=>'File HTML','class'=>'i-File-HTML',],
                ['title'=>'File JPG','class'=>'i-File-JPG',],
                ['title'=>'File Link','class'=>'i-File-Link',],
                ['title'=>'File Loading','class'=>'i-File-Loading',],
                ['title'=>'File Lock','class'=>'i-File-Lock',],
                ['title'=>'File Love','class'=>'i-File-Love',],
                ['title'=>'File Music','class'=>'i-File-Music',],
                ['title'=>'File Network','class'=>'i-File-Network',],
                ['title'=>'File Pictures','class'=>'i-File-Pictures',],
                ['title'=>'File Pie','class'=>'i-File-Pie',],
                ['title'=>'File Presentation','class'=>'i-File-Presentation',],
                ['title'=>'File Refresh','class'=>'i-File-Refresh',],
                ['title'=>'File Search','class'=>'i-File-Search',],
                ['title'=>'File Settings','class'=>'i-File-Settings',],
                ['title'=>'File Share','class'=>'i-File-Share',],
                ['title'=>'File Text Image','class'=>'i-File-Text--Image',],
                ['title'=>'File Trash','class'=>'i-File-Trash',],
                ['title'=>'File TXT','class'=>'i-File-TXT',],
                ['title'=>'File Upload','class'=>'i-File-Upload',],
                ['title'=>'File Video','class'=>'i-File-Video',],
                ['title'=>'File Word','class'=>'i-File-Word',],
                ['title'=>'File Zip','class'=>'i-File-Zip',],
                ['title'=>'File','class'=>'i-File',],
                ['title'=>'Files','class'=>'i-Files',],
                ['title'=>'Remove-File','class'=>'i-Remove-File',],
                ['title'=>'Angry','class'=>'i-Angry',],
                ['title'=>'Cap','class'=>'i-Cap',],
                ['title'=>'Clown','class'=>'i-Clown',],
                ['title'=>'Confused','class'=>'i-Confused',],
                ['title'=>'Cool','class'=>'i-Cool',],
                ['title'=>'Crying','class'=>'i-Crying',],
                ['title'=>'Depression','class'=>'i-Depression',],
                ['title'=>'Eyeglasses Smiley','class'=>'i-Eyeglasses-Smiley',],
                ['title'=>'Eyeglasses Smiley','class'=>'i-Eyeglasses-Smiley',],
                ['title'=>'Geek 1','class'=>'i-Geek1',],
                ['title'=>'Happy','class'=>'i-Happy',],
                ['title'=>'Humor','class'=>'i-Humor',],
                ['title'=>'Laughing','class'=>'i-Laughing',],
                ['title'=>'Love 1','class'=>'i-Love1',],
                ['title'=>'Money','class'=>'i-Money',],
                ['title'=>'Moustache Smiley','class'=>'i-Moustache-Smiley',],
                ['title'=>'Smile','class'=>'i-Smile',],
                ['title'=>'Sunglasses Smiley 2','class'=>'i-Sunglasses-Smiley-2',],
                ['title'=>'Sunglasses Smiley','class'=>'i-Sunglasses-Smiley',],
                ['title'=>'Surprise','class'=>'i-Surprise',],
                ['title'=>'Thumbs Down Smiley','class'=>'i-Thumbs-Down-Smiley',],
                ['title'=>'Thumbs Up Smiley','class'=>'i-Thumbs-Up-Smiley',],
                ['title'=>'Tongue','class'=>'i-Tongue',],
                ['title'=>'At Sign','class'=>'i-At-Sign',],
                ['title'=>'Box Full','class'=>'i-Box-Full',],
                ['title'=>'Empty Box','class'=>'i-Empty-Box',],
                ['title'=>'Envelope 2','class'=>'i-Envelope-2',],
                ['title'=>'Envelope','class'=>'.-Envelope',],
                ['title'=>'Inbox Empty','class'=>'i-Inbox-Empty',],
                ['title'=>'Inbox Full','class'=>'i-Inbox-Full',],
                ['title'=>'Inbox Into','class'=>'i-Inbox-Into',],
                ['title'=>'Inbox Out','class'=>'i-Inbox-Out',],
                ['title'=>'Letter Close','class'=>'i-Letter-Close',],
                ['title'=>'Letter Open','class'=>'i-Letter-Open',],
                ['title'=>'Letter Sent','class'=>'i-Letter-Sent',],
                ['title'=>'Mail 2','class'=>'i-Mail-2',],
                ['title'=>'Mail 3','class'=>'i-Mail-3',],
                ['title'=>'Mail Add-','class'=>'i-Mail-Add',],
                ['title'=>'Mail Attachement','class'=>'i-Mail-Attachement',],
                ['title'=>'Mail Block','class'=>'i-Mail-Block',],
                ['title'=>'Mail Delete','class'=>'i-Mail-Delete',],
                ['title'=>'Mail Favorite','class'=>'i-Mail-Favorite',],
                ['title'=>'Mail Forward','class'=>'i-Mail-Forward',],
                ['title'=>'Mail Gallery','class'=>'i-Mail-Gallery',],
                ['title'=>'Mail Inbox','class'=>'i-Mail-Inbox',],
                ['title'=>'Mail Link','class'=>'i-Mail-Link',],
                ['title'=>'Mail Lock','class'=>'i-Mail-Lock',],
                ['title'=>'Mail Love','class'=>'i-Mail-Love',],
                ['title'=>'Mail Money','class'=>'i-Mail-Money',],
                ['title'=>'Mail Open','class'=>'i-Mail-Open',],
                ['title'=>'Mail Outbox','class'=>'i-Mail-Outbox',],
                ['title'=>'Mail Password','class'=>'i-Mail-Password',],
                ['title'=>'Mail Photo','class'=>'i-Mail-Photo',],
                ['title'=>'Mail Read','class'=>'i-Mail-Read',],
                ['title'=>'Mail Remove-x','class'=>'i-Mail-Remove-x',],
                ['title'=>'Mail Reply-All','class'=>'i-Mail-Reply-All',],
                ['title'=>'Mail Reply','class'=>'i-Mail-Reply',],
                ['title'=>'Mail Search','class'=>'i-Mail-Search',],
                ['title'=>'Mail Send','class'=>'i-Mail-Send',],
                ['title'=>'Mail Settings','class'=>'i-Mail-Settings',],
                ['title'=>'Mail Unread','class'=>'i-Mail-Unread',],
                ['title'=>'Mail Video','class'=>'i-Mail-Video',],
                ['title'=>'Mail with-At-Sign','class'=>'i-Mail-with-At-Sign',],
                ['title'=>'Mail With-Cursors','class'=>'i-Mail-With-Cursors',],
                ['title'=>'Mail','class'=>'i-Mail',],
                ['title'=>'Mailbox Empty','class'=>'i-Mailbox-Empty',],
                ['title'=>'Mailbox Full','class'=>'i-Mailbox-Full',],
                ['title'=>'New-Mail','class'=>'i-New-Mail',],
                ['title'=>'Post Mail 2','class'=>'i-Post-Mail-2',],
                ['title'=>'Post Mail','class'=>'i-Post-Mail',],
                ['title'=>'Spam Mail','class'=>'i-Spam-Mail',],
                ['title'=>'Stamp 2','class'=>'i-Stamp-2',],
                ['title'=>'Stamp','class'=>'i-Stamp',],
                ['title'=>'Voicemail','class'=>'i-Voicemail',],
                ['title'=>'Alpha','class'=>'i-Alpha',],
                ['title'=>'Beta','class'=>'i-Beta',],
                ['title'=>'Blackboard','class'=>'i-Blackboard',],
                ['title'=>'Book','class'=>'i-Book',],
                ['title'=>'Bookmark','class'=>'i-Bookmark',],
                ['title'=>'Diploma 2','class'=>'i-Diploma-2',],
                ['title'=>'Diploma','class'=>'i-Diploma',],
                ['title'=>'Eraser 2','class'=>'i-Eraser-2',],
                ['title'=>'Notepad 2','class'=>'i-Notepad-2',],
                ['title'=>'Notepad','class'=>'i-Notepad',],
                ['title'=>'Open Book','class'=>'i-Open-Book',],
                ['title'=>'Pen 2','class'=>'i-Pen-2',],
                ['title'=>'Pen 3','class'=>'i-Pen-3',],
                ['title'=>'Pen 4','class'=>'i-Pen-4',],
                ['title'=>'Pen 5','class'=>'i-Pen-5',],
                ['title'=>'Pen 6','class'=>'i-Pen-6',],
                ['title'=>'Pi','class'=>'i-Pi',],
                ['title'=>'Pipette','class'=>'i-Pipette',],
                ['title'=>'Quill 2','class'=>'i-Quill-2',],
                ['title'=>'Quill 3','class'=>'i-Quill-3',],
                ['title'=>'Quill','class'=>'i-Quill',],
                ['title'=>'Spell Check ABC','class'=>'i-Spell-Check-ABC',],
                ['title'=>'Spell Check','class'=>'i-Spell-Check',],
                ['title'=>'Stapler','class'=>'i-Stapler',],
                ['title'=>'Student Hat 2','class'=>'i-Student-Hat-2',],
                ['title'=>'Student Hat','class'=>'i-Student-Hat',],
                ['title'=>'Sum 1','class'=>'i-Sum1',],
                ['title'=>'University','class'=>'i-University',],
                ['title'=>'Computer 2','class'=>'i-Computer-2',],
                ['title'=>'Monitor 2','class'=>'i-Monitor-2',],
                ['title'=>'Monitor 3','class'=>'i-Monitor-3',],
                ['title'=>'Monitor 5','class'=>'i-Monitor-5',],
                ['title'=>'Monitor Vertical','class'=>'i-Monitor-Vertical',],
                ['title'=>'Orientation 2','class'=>'i-Orientation-2',],
                ['title'=>'Board','class'=>'i-Board',],
                ['title'=>'Brush','class'=>'i-Brush',],
                ['title'=>'Clamp','class'=>'i-Clamp',],
                ['title'=>'CMYK','class'=>'i-CMYK',],
                ['title'=>'Idea','class'=>'i-Idea',],
                ['title'=>'Knife 1','class'=>'i-Knife1',],
                ['title'=>'Marker','class'=>'i-Marker',],
                ['title'=>'Note','class'=>'i-Note',],
                ['title'=>'Paintbrush','class'=>'i-Paintbrush',],
                ['title'=>'Vector','class'=>'i-Vector',],
                ['title'=>'Big Data','class'=>'i-Big-Data',],
                ['title'=>'Data Backup','class'=>'i-Data-Backup',],
                ['title'=>'Data Block','class'=>'i-Data-Block',],
                ['title'=>'Data Center','class'=>'i-Data-Center',],
                ['title'=>'Data Clock','class'=>'i-Data-Clock',],
                ['title'=>'Data Cloud','class'=>'i-Data-Cloud',],
                ['title'=>'Data Compress','class'=>'i-Data-Compress',],
                ['title'=>'Data Copy','class'=>'i-Data-Copy',],
                ['title'=>'Data Download','class'=>'i-Data-Download',],
                ['title'=>'Data Financial','class'=>'i-Data-Financial',],
                ['title'=>'Data Key','class'=>'i-Data-Key',],
                ['title'=>'Data Lock','class'=>'i-Data-Lock',],
                ['title'=>'Data Network','class'=>'i-Data-Network',],
                ['title'=>'Data Password','class'=>'i-Data-Password',],
                ['title'=>'Data Power','class'=>'i-Data-Power',],
                ['title'=>'Data Refresh','class'=>'i-Data-Refresh',],
                ['title'=>'Data Save','class'=>'i-Data-Save',],
                ['title'=>'Data Search','class'=>'i-Data-Search',],
                ['title'=>'Data Security','class'=>'i-Data-Security',],
                ['title'=>'Data Settings','class'=>'i-Data-Settings',],
                ['title'=>'Data Sharing','class'=>'i-Data-Sharing',],
                ['title'=>'Data Shield','class'=>'i-Data-Shield',],
                ['title'=>'Data Signal','class'=>'i-Data-Signal',],
                ['title'=>'Data Storage','class'=>'i-Data-Storage',],
                ['title'=>'Data Stream','class'=>'i-Data-Stream',],
                ['title'=>'Data Transfer','class'=>'i-Data-Transfer',],
                ['title'=>'Data Unlock','class'=>'i-Data-Unlock',],
                ['title'=>'Data Upload','class'=>'i-Data-Upload',],
                ['title'=>'Data Yes','class'=>'i-Data-Yes',],
                ['title'=>'Data','class'=>'i-Data',],
                ['title'=>'Hub','class'=>'i-Hub',],
                ['title'=>'Address Book 2','class'=>'i-Address-Book-2',],
                ['title'=>'Address Book','class'=>'i-Address-Book',],
                ['title'=>'Bell 1','class'=>'i-Bell1',],
                ['title'=>'Bird Delivering Letter','class'=>'i-Bird-Delivering-Letter',],
                ['title'=>'Communication Tower 2','class'=>'i-Communication-Tower-2',],
                ['title'=>'Communication Tower','class'=>'i-Communication-Tower',],
                ['title'=>'Fax','class'=>'i-Fax',],
                ['title'=>'Megaphone','class'=>'i-Megaphone',],
                ['title'=>'Newspaper 2','class'=>'i-Newspaper-2',],
                ['title'=>'Newspaper','class'=>'i-Newspaper',],
                ['title'=>'Old Telephone','class'=>'i-Old-Telephone',],
                ['title'=>'Plastic Cup Phone 2','class'=>'i-Plastic-Cup-Phone-2',],
                ['title'=>'Plastic Cup Phone','class'=>'i-Plastic-Cup-Phone',],
                ['title'=>'Router 2','class'=>'i-Router-2',],
                ['title'=>'Router','class'=>'i-Router',],
                ['title'=>'Telephone 2','class'=>'i-Telephone-2',],
                ['title'=>'Telephone','class'=>'i-Telephone',],
                ['title'=>'VPN','class'=>'i-VPN',],
                ['title'=>'Walkie Talkie','class'=>'i-Walkie-Talkie',],
                ['title'=>'Wifi 2','class'=>'i-Wifi-2',],
                ['title'=>'Wifi','class'=>'i-Wifi',],
                ['title'=>'Wireless','class'=>'i-Wireless',],
                ['title'=>'Block Cloud','class'=>'i-Block-Cloud',],
                ['title'=>'Cloud','class'=>'i-Cloud',],
                ['title'=>'Cloud ','class'=>'i-Cloud-',],
                ['title'=>'Cloud Camera','class'=>'i-Cloud-Camera',],
                ['title'=>'Cloud Computer','class'=>'i-Cloud-Computer',],
                ['title'=>'Cloud Email','class'=>'i-Cloud-Email',],
                ['title'=>'Cloud Laptop','class'=>'i-Cloud-Laptop',],
                ['title'=>'Cloud Lock','class'=>'i-Cloud-Lock',],
                ['title'=>'Cloud Music','class'=>'i-Cloud-Music',],
                ['title'=>'Cloud Picture','class'=>'i-Cloud-Picture',],
                ['title'=>'Cloud Remove','class'=>'i-Cloud-Remove',],
                ['title'=>'Cloud Secure','class'=>'i-Cloud-Secure',],
                ['title'=>'Cloud Settings','class'=>'i-Cloud-Settings',],
                ['title'=>'Cloud Smartphone','class'=>'i-Cloud-Smartphone',],
                ['title'=>'Cloud Tablet','class'=>'i-Cloud-Tablet',],
                ['title'=>'Cloud Video','class'=>'i-Cloud-Video',],
                ['title'=>'Cloud1','class'=>'i-Cloud1',],
                ['title'=>'Clouds','class'=>'i-Clouds',],
                ['title'=>'Device Sync with Cloud','class'=>'i-Device-Sync-with-Cloud',],
                ['title'=>'Download from Cloud','class'=>'i-Download-from-Cloud',],
                ['title'=>'People on Cloud','class'=>'i-People-on-Cloud',],
                ['title'=>'Search on Cloud','class'=>'i-Search-on-Cloud',],
                ['title'=>'Share on Cloud','class'=>'i-Share-on-Cloud',],
                ['title'=>'Belt 3','class'=>'i-Belt-3',],
                ['title'=>'Wallet 2','class'=>'i-Wallet-2',],
                ['title'=>'Womans Underwear-2','class'=>'i-Womans-Underwear-2',],
                ['title'=>'Womans Underwear','class'=>'i-Womans-Underwear',],
                ['title'=>'Dec','class'=>'i-Dec',],
                ['title'=>'Angel','class'=>'i-Angel',],
                ['title'=>'Bow1','class'=>'i-Bow1',],
                ['title'=>'Christmas Ball','class'=>'i-Christmas-Ball',],
                ['title'=>'Christmas Bell','class'=>'i-Christmas-Bell',],
                ['title'=>'Christmas Candle','class'=>'i-Christmas-Candle',],
                ['title'=>'Christmas Hat','class'=>'i-Christmas-Hat',],
                ['title'=>'Present','class'=>'i-Present',],
                ['title'=>'Tactic','class'=>'i-Tactic',],
                ['title'=>'AMX','class'=>'i-AMX',],
                ['title'=>'ATM','class'=>'i-ATM',],
                ['title'=>'Bar Chart 2','class'=>'i-Bar-Chart-2',],
                ['title'=>'Bar Chart 3','class'=>'i-Bar-Chart-3',],
                ['title'=>'Bar Chart 4','class'=>'i-Bar-Chart-4',],
                ['title'=>'Bar Chart 5','class'=>'i-Bar-Chart-5',],
                ['title'=>'Bar-Chart','class'=>'i-Bar-Chart',],
                ['title'=>'Calculator 2','class'=>'i-Calculator-2',],
                ['title'=>'Calculator 3','class'=>'i-Calculator-3',],
                ['title'=>'Calculator','class'=>'i-Calculator',],
                ['title'=>'Calendar 2','class'=>'i-Calendar-2',],
                ['title'=>'Calendar 3','class'=>'i-Calendar-3',],
                ['title'=>'Calendar 4','class'=>'i-Calendar-4',],
                ['title'=>'Calendar','class'=>'i-Calendar',],
                ['title'=>'Claps','class'=>'i-Claps',],
                ['title'=>'Coin','class'=>'i-Coin',],
                ['title'=>'Coins 2','class'=>'i-Coins-2',],
                ['title'=>'Coins 3','class'=>'i-Coins-3',],
                ['title'=>'Coins','class'=>'i-Coins',],
                ['title'=>'Credit Card 2','class'=>'i-Credit-Card-2',],
                ['title'=>'Credit Card 3','class'=>'i-Credit-Card-3',],
                ['title'=>'Credit Card','class'=>'i-Credit-Card',],
                ['title'=>'Diamond','class'=>'i-Diamond',],
                ['title'=>'Dollar Sign 2','class'=>'i-Dollar-Sign-2',],
                ['title'=>'Dollar Sign','class'=>'i-Dollar-Sign',],
                ['title'=>'Dollar','class'=>'i-Dollar',],
                ['title'=>'Euro Sign 2','class'=>'i-Euro-Sign-2',],
                ['title'=>'Euro Sign','class'=>'i-Euro-Sign',],
                ['title'=>'Euro','class'=>'i-Euro',],
                ['title'=>'Financial','class'=>'i-Financial',],
                ['title'=>'Handshake','class'=>'i-Handshake',],
                ['title'=>'Line Chart 2','class'=>'i-Line-Chart-2',],
                ['title'=>'Line Chart 3','class'=>'i-Line-Chart-3',],
                ['title'=>'Line Chart 4','class'=>'i-Line-Chart-4',],
                ['title'=>'Line Chart','class'=>'i-Line-Chart',],
                ['title'=>'Money 2','class'=>'i-Money-2',],
                ['title'=>'Money Bag','class'=>'i-Money-Bag',],
                ['title'=>'Money 1','class'=>'i-Money1',],
                ['title'=>'Pie Chart 2','class'=>'i-Pie-Chart-2',],
                ['title'=>'Pie Chart 3','class'=>'i-Pie-Chart-3',],
                ['title'=>'Pie Chart','class'=>'i-Pie-Chart',],
                ['title'=>'Pound Sign 2','class'=>'i-Pound-Sign-2',],
                ['title'=>'Pound Sign','class'=>'i-Pound-Sign',],
                ['title'=>'Pound','class'=>'i-Pound',],
                ['title'=>'Safe Box 1','class'=>'i-Safe-Box1',],
                ['title'=>'Token','class'=>'i-Token-',],
                ['title'=>'Visa','class'=>'i-Visa',],
                ['title'=>'Wallet 21','class'=>'i-Wallet-21',],
                ['title'=>'Wallet','class'=>'i-Wallet',],
                ['title'=>'Bank','class'=>'i-Bank',],
                ['title'=>'Building','class'=>'i-Building',],
                ['title'=>'Clothing Store','class'=>'i-Clothing-Store',],
                ['title'=>'Column 2','class'=>'i-Column-2',],
                ['title'=>'Column 3','class'=>'i-Column-3',],
                ['title'=>'Column','class'=>'i-Column',],
                ['title'=>'Door','class'=>'i-Door',],
                ['title'=>'Factory 1','class'=>'i-Factory1',],
                ['title'=>'Home 2','class'=>'i-Home-2',],
                ['title'=>'Home 4','class'=>'i-Home-4',],
                ['title'=>'Home 1','class'=>'i-Home1',],
                ['title'=>'Hospital 1','class'=>'i-Hospital1',],
                ['title'=>'Hotel','class'=>'i-Hotel',],
                ['title'=>'Japanese Gate','class'=>'i-Japanese-Gate',],
                ['title'=>'Police Station','class'=>'i-Police-Station',],
                ['title'=>'Post Office','class'=>'i-Post-Office',],
                ['title'=>'Structure','class'=>'i-Structure',],
                ['title'=>'Tower 2','class'=>'i-Tower-2',],
                ['title'=>'Tower','class'=>'i-Tower',],
                ['title'=>'University 1','class'=>'i-University1',],
                ['title'=>'Window','class'=>'i-Window',],
                ['title'=>'Android','class'=>'i-Android',],
                ['title'=>'Chrome','class'=>'i-Chrome',],
                ['title'=>'Debian','class'=>'i-Debian',],
                ['title'=>'Firefox','class'=>'i-Firefox',],
                ['title'=>'Internet-Explorer','class'=>'i-Internet-Explorer',],
                ['title'=>'iOS-Apple','class'=>'i-iOS-Apple',],
                ['title'=>'Linux','class'=>'i-Linux',],
                ['title'=>'Netscape','class'=>'i-Netscape',],
                ['title'=>'Opera','class'=>'i-Opera',],
                ['title'=>'Windows Microsoft','class'=>'i-Windows-Microsoft',],
                ['title'=>'Brain1','class'=>'i-Brain1',],
                ['title'=>'Cardiovascular','class'=>'i-Cardiovascular',],
                ['title'=>'Elbow','class'=>'i-Elbow',],
                ['title'=>'Eye Visible','class'=>'i-Eye-Visible',],
                ['title'=>'Eye 1','class'=>'i-Eye1',],
                ['title'=>'Eyebrow 2','class'=>'i-Eyebrow-2',],
                ['title'=>'Eyebrow','class'=>'i-Eyebrow',],
                ['title'=>'Face-Style 2','class'=>'i-Face-Style-2',],
                ['title'=>'Face-Style 3','class'=>'i-Face-Style-3',],
                ['title'=>'Face-Style 4','class'=>'i-Face-Style-4',],
                ['title'=>'Face-Style 5','class'=>'i-Face-Style-5',],
                ['title'=>'Face-Style 6','class'=>'i-Face-Style-6',],
                ['title'=>'Finger','class'=>'i-Finger',],
                ['title'=>'Fingerprint 2','class'=>'i-Fingerprint-2',],
                ['title'=>'Fingerprint','class'=>'i-Fingerprint',],
                ['title'=>'Foot','class'=>'i-Foot',],
                ['title'=>'Hand','class'=>'i-Hand',],
                ['title'=>'Heart 1','class'=>'i-Heart1',],
                ['title'=>'Leg','class'=>'i-Leg',],
                ['title'=>'Mustache 31','class'=>'i-Mustache-31',],
                ['title'=>'Mustache 4','class'=>'i-Mustache-4',],
                ['title'=>'Arrow Back 2','class'=>'i-Arrow-Back-2',],
                ['title'=>'Arrow Back 3','class'=>'i-Arrow-Back-3',],
                ['title'=>'Arrow Back','class'=>'i-Arrow-Back',],
                ['title'=>'Arrow Down 2','class'=>'i-Arrow-Down-2',],
                ['title'=>'Arrow Down 3','class'=>'i-Arrow-Down-3',],
                ['title'=>'Arrow Down in Circle','class'=>'i-Arrow-Down-in-Circle',],
                ['title'=>'Arrow Down','class'=>'i-Arrow-Down',],
                ['title'=>'Arrow Forward 2','class'=>'i-Arrow-Forward-2',],
                ['title'=>'Arrow Forward','class'=>'i-Arrow-Forward',],
                ['title'=>'Arrow Left 2','class'=>'i-Arrow-Left-2',],
                ['title'=>'Arrow Left in Circle','class'=>'i-Arrow-Left-in-Circle',],
                ['title'=>'Arrow Left','class'=>'i-Arrow-Left',],
                ['title'=>'Arrow Next','class'=>'i-Arrow-Next',],
                ['title'=>'Arrow Refresh 2','class'=>'i-Arrow-Refresh-2',],
                ['title'=>'Arrow Refresh','class'=>'i-Arrow-Refresh',],
                ['title'=>'Arrow Right 2','class'=>'i-Arrow-Right-2',],
                ['title'=>'Arrow Right in Circle','class'=>'i-Arrow-Right-in-Circle',],
                ['title'=>'Arrow Right','class'=>'nhojunior',],
                ['title'=>'Arrow Turn Left','class'=>'i-Arrow-Turn-Left',],
                ['title'=>'Arrow Turn Right','class'=>'i-Arrow-Turn-Right',],
                ['title'=>'Arrow Up 2','class'=>'i-Arrow-Up-2',],
                ['title'=>'Arrow Up 3','class'=>'i-Arrow-Up-3',],
                ['title'=>'Arrow Up in Circle','class'=>'i-Arrow-Up-in-Circle',],
                ['title'=>'Arrow Up:','class'=>'i-Arrow-Up',],
                ['title'=>'Arrow X Left','class'=>'i-Arrow-X-Left',],
                ['title'=>'Arrow X Right','class'=>'i-Arrow-X-Right',],
                ['title'=>'Bottom To Top','class'=>'i-Bottom-To-Top',],
                ['title'=>'Down 2','class'=>'i-Down-2',],
                ['title'=>'Down 3','class'=>'i-Down-3',],
                ['title'=>'Down 1','class'=>'i-Down1',],
                ['title'=>'Download 1','class'=>'i-Download1',],
                ['title'=>'End 1','class'=>'i-End1',],
                ['title'=>'Fit To 2','class'=>'i-Fit-To-2',],
                ['title'=>'Fit To','class'=>'i-Fit-To',],
                ['title'=>'Full Screen 2','class'=>'i-Full-Screen-2',],
                ['title'=>'Full Screen','class'=>'i-Full-Screen',],
                ['title'=>'Go Bottom','class'=>'i-Go-Bottom',],
                ['title'=>'Go Top','class'=>'i-Go-Top',],
                ['title'=>'Left - Right 3','class'=>'i-Left---Right-3',],
                ['title'=>'Left - Right','class'=>'i-Left---Right',],
                ['title'=>'Left 2','class'=>'i-Left-2',],
                ['title'=>'Left 3','class'=>'i-Left-3',],
                ['title'=>'Left To Right','class'=>'i-Left-To-Right',],
                ['title'=>'Left 1','class'=>'i-Left1',],
                ['title'=>'Loop','class'=>'i-Loop',],
                ['title'=>'Navigat Start','class'=>'i-Navigat-Start',],
                ['title'=>'Navigate End','class'=>'i-Navigate-End',],
                ['title'=>'Reload 2','class'=>'i-Reload-2',],
                ['title'=>'Reload 1','class'=>'i-Reload1',],
                ['title'=>'Repeat 21','class'=>'i-Repeat-21',],
                ['title'=>'Repeat 3','class'=>'i-Repeat-3',],
                ['title'=>'Repeat 4','class'=>'i-Repeat-4',],
                ['title'=>'Repeat 2','class'=>'i-Repeat2',],
                ['title'=>'Right 2','class'=>'i-Right-2',],
                ['title'=>'Right 3','class'=>'i-Right-3',],
                ['title'=>'Right To Left','class'=>'i-Right-To-Left',],
                ['title'=>'Right 1','class'=>'i-Right1',],
                ['title'=>'Shuffle 21','class'=>'i-Shuffle-21',],
                ['title'=>'Shuffle 1','class'=>'i-Shuffle1',],
                ['title'=>'Start 1','class'=>'i-Start1',],
                ['title'=>'Sync','class'=>'i-Sync',],
                ['title'=>'To Bottom 2','class'=>'i-To-Bottom-2',],
                ['title'=>'To Bottom','class'=>'i-To-Bottom',],
                ['title'=>'To Left','class'=>'i-To-Left',],
                ['title'=>'To Right','class'=>'i-To-Right',],
                ['title'=>'To Top 2','class'=>'i-To-Top-2',],
                ['title'=>'To Top','class'=>'i-To-Top',],
                ['title'=>'Top To Bottom','class'=>'i-Top-To-Bottom',],
                ['title'=>'Triangle Arrow Down','class'=>'i-Triangle-Arrow-Down',],
                ['title'=>'Triangle Arrow Left','class'=>'i-Triangle-Arrow-Left',],
                ['title'=>'Triangle Arrow Right','class'=>'i-Triangle-Arrow-Right',],
                ['title'=>'Triangle Arrow Up','class'=>'i-Triangle-Arrow-Up',],
                ['title'=>'Turn Down 2','class'=>'i-Turn-Down-2',],
                ['title'=>'Turn Down From Left','class'=>'i-Turn-Down-From-Left',],
                ['title'=>'Turn Down From Right','class'=>'i-Turn-Down-From-Right',],
                ['title'=>'Turn Down','class'=>'i-Turn-Down',],
                ['title'=>'Turn Left 3','class'=>'i-Turn-Left-3',],
                ['title'=>'Turn Left','class'=>'i-Turn-Left',],
                ['title'=>'Turn Right 3','class'=>'i-Turn-Right-3',],
                ['title'=>'Turn Right','class'=>'i-Turn-Right',],
                ['title'=>'Turn Up 2','class'=>'i-Turn-Up-2',],
                ['title'=>'Turn Up','class'=>'i-Turn-Up',],
                ['title'=>'Up - Down 3','class'=>'i-Up---Down-3',],
                ['title'=>'Up - Down','class'=>'i-Up---Down',],
                ['title'=>'Up 2','class'=>'i-Up-2',],
                ['title'=>'Up 3','class'=>'i-Up-3',],
                ['title'=>'Up 1','class'=>'i-Up1',],
                ['title'=>'Upload1','class'=>'i-Upload1',],
                ['title'=>'Arrow Around','class'=>'i-Arrow-Around',],
                ['title'=>'Arrow Barrier','class'=>'i-Arrow-Barrier',],
                ['title'=>'Arrow Circle','class'=>'i-Arrow-Circle',],
                ['title'=>'Arrow Cross','class'=>'i-Arrow-Cross',],
                ['title'=>'Arrow Fork','class'=>'i-Arrow-Fork',],
                ['title'=>'Arrow From','class'=>'i-Arrow-From',],
                ['title'=>'Arrow Inside 45','class'=>'i-Arrow-Inside-45',],
                ['title'=>'Arrow Inside Gap-45','class'=>'i-Arrow-Inside-Gap-45',],
                ['title'=>'Arrow Inside Gap','class'=>'i-Arrow-Inside-Gap',],
                ['title'=>'Arrow Inside','class'=>'i-Arrow-Inside',],
                ['title'=>'Arrow Loop','class'=>'i-Arrow-Loop',],
                ['title'=>'Arrow Mix','class'=>'i-Arrow-Mix',],
                ['title'=>'Arrow Out Left','class'=>'i-Arrow-Out-Left',],
                ['title'=>'Arrow Out Right','class'=>'i-Arrow-Out-Right',],
                ['title'=>'Arrow Outside 45','class'=>'i-Arrow-Outside-45',],
                ['title'=>'Arrow Outside Gap 45','class'=>'i-Arrow-Outside-Gap-45',],
                ['title'=>'Arrow Outside Gap','class'=>'i-Arrow-Outside-Gap',],
                ['title'=>'Arrow Outside','class'=>'i-Arrow-Outside',],
                ['title'=>'Arrow Over','class'=>'i-Arrow-Over',],
                ['title'=>'Arrow Shuffle','class'=>'i-Arrow-Shuffle',],
                ['title'=>'Resize','class'=>'i-Resize',],
                ['title'=>'Chicken','class'=>'i-Chicken',],
                ['title'=>'Align Justify All','class'=>'i-Align-Justify-All',],
                ['title'=>'Align Justify Center','class'=>'i-Align-Justify-Center',],
                ['title'=>'Align Justify Left','class'=>'i-Align-Justify-Left',],
                ['title'=>'Align Justify Right','class'=>'i-Align-Justify-Right',],
                ['title'=>'Align Left','class'=>'i-Align-Left',],
                ['title'=>'Align Right','class'=>'i-Align-Right',],
            ]);
        }
    }
