<?php
    namespace Database\Seeders;

    use Illuminate\Database\Console\Seeds\WithoutModelEvents;
    use Illuminate\Database\Seeder;
    use Illuminate\Support\Facades\DB as FacadesDB;

    class ImageSeeder extends Seeder {
        public function run(): void {
            FacadesDB::table('images')->insert([
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-dddd-16-09-2025-06-09-29.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/publisher-Cacete-16-09-2025-06-09-45.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/user-ggggg-16-09-2025-06-09-57.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 04','slug'=>'imagem-04','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-fffff-16-09-2025-06-09-48.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 05','slug'=>'imagem-05','descr'=>'Teste de Imagens','image'=>'uploads/users/2/publisher-TEste-15-09-2025-22-09-05.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 06','slug'=>'imagem-06','descr'=>'Teste de Imagens','image'=>'uploads/users/3/user-teste-16-09-2025-04-09-44.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-Teste 2 milhões-16-09-2025-06-09-08.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/awakening.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof401.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste2-12-09-2025-01-09-56.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_01.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof402.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 04','slug'=>'imagem-04','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-01.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 05','slug'=>'imagem-05','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_02.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 06','slug'=>'imagem-06','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof403.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-15.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_03.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof404.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-18.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_04.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof405.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 04','slug'=>'imagem-04','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-fffff-16-09-2025-06-09-48.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 05','slug'=>'imagem-05','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_05.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 06','slug'=>'imagem-06','descr'=>'Teste de Imagens','image'=>'uploads/users/3/LeagueHall.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-22.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_06.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/breathoffireiv.png','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste2-12-09-2025-01-09-56.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_07.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/about-03.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 04','slug'=>'imagem-04','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-32.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 05','slug'=>'imagem-05','descr'=>'Teste de Imagens','image'=>'uploads/users/2/intro.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 06','slug'=>'imagem-06','descr'=>'Teste de Imagens','image'=>'uploads/users/3/DC-Universe-Online.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-53.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/Sem-Título-2.png','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/gcc-site-005.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-dddd-16-09-2025-06-09-29.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/publisher-Cacete-16-09-2025-06-09-45.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/user-ggggg-16-09-2025-06-09-57.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 04','slug'=>'imagem-04','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-fffff-16-09-2025-06-09-48.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 05','slug'=>'imagem-05','descr'=>'Teste de Imagens','image'=>'uploads/users/2/publisher-TEste-15-09-2025-22-09-05.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 06','slug'=>'imagem-06','descr'=>'Teste de Imagens','image'=>'uploads/users/3/user-teste-16-09-2025-04-09-44.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-Teste 2 milhões-16-09-2025-06-09-08.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/awakening.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof401.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste2-12-09-2025-01-09-56.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_01.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof402.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 04','slug'=>'imagem-04','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-01.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 05','slug'=>'imagem-05','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_02.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 06','slug'=>'imagem-06','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof403.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-15.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_03.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof404.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-18.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_04.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/bof405.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 04','slug'=>'imagem-04','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-fffff-16-09-2025-06-09-48.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 05','slug'=>'imagem-05','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_05.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 06','slug'=>'imagem-06','descr'=>'Teste de Imagens','image'=>'uploads/users/3/LeagueHall.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-22.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_06.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/breathoffireiv.png','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste2-12-09-2025-01-09-56.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/heart_soul_07.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/about-03.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 04','slug'=>'imagem-04','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-32.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 05','slug'=>'imagem-05','descr'=>'Teste de Imagens','image'=>'uploads/users/2/intro.jpg','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 06','slug'=>'imagem-06','descr'=>'Teste de Imagens','image'=>'uploads/users/3/DC-Universe-Online.jpg','user_id'=>3,'created_at'=> now(),],
                ['title'=>'Imagem 01','slug'=>'imagem-01','descr'=>'Teste de Imagens','image'=>'uploads/users/1/nhojunior-teste-14-09-2025-01-09-53.jpg','user_id'=>1,'created_at'=> now(),],
                ['title'=>'Imagem 02','slug'=>'imagem-02','descr'=>'Teste de Imagens','image'=>'uploads/users/2/Sem-Título-2.png','user_id'=>2,'created_at'=> now(),],
                ['title'=>'Imagem 03','slug'=>'imagem-03','descr'=>'Teste de Imagens','image'=>'uploads/users/3/gcc-site-005.jpg','user_id'=>3,'created_at'=> now(),],
            ]);
        }
    }
